apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: hmatsu-admin
  description: The HMATSU administrators
spec:
  type: team
  profile:
    displayName: HMATSU Admin
    email: infrastructure@example.com
  children: []
  members:
    - aungheinkyaw11
